version: "3.8"

services:
  atendimento-service:
    build:
      context: .
      dockerfile: atendimento-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d3ft68umcj7s73et2v40-a:5432/attendance_db_lhsz
      SPRING_DATASOURCE_USERNAME: attendance_db_lhsz_user
      SPRING_DATASOURCE_PASSWORD: wct6r2f1UvYQo9kwVet0tSxlY539FPsv
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - tonynet

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d3ft68umcj7s73et2v40-a:5432/attendance_db_lhsz
      SPRING_DATASOURCE_USERNAME: attendance_db_lhsz_user
      SPRING_DATASOURCE_PASSWORD: wct6r2f1UvYQo9kwVet0tSxlY539FPsv
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - tonynet

  cliente-service:
    build:
      context: .
      dockerfile: cliente-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d3ft68umcj7s73et2v40-a:5432/attendance_db_lhsz
      SPRING_DATASOURCE_USERNAME: attendance_db_lhsz_user
      SPRING_DATASOURCE_PASSWORD: wct6r2f1UvYQo9kwVet0tSxlY539FPsv
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - tonynet

networks:
  tonynet:
